apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  creationTimestamp: null
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 1
  name: service-account
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/cloud-mysql/servicebindings/service-account
spec:
  externalID: 7bd0779b-5af7-11e8-b47f-0a580a37d309
  instanceRef:
    name: service-account
  parameters: {}
  secretName: service-account
status:
  asyncOpInProgress: false
  conditions: []
  orphanMitigationInProgress: false
  reconciledGeneration: 0
  unbindStatus: NotRequired
